### PR TITLE
add an example

### PR DESCRIPTION
**Pull request by nopeless**

### CODE REVIEW

**Comment by doublevcodes** [comment]
I've added prefix to the required constants locally so could you please add that in: 
**Required**
- `bot-token`
- `prefix`
**Optional**
Same as before

**Comment by nopeless** [comment]
you know you can request changes right

**Comment by doublevcodes** [comment]
no im new to this im gonna do that now

**Review by doublevcodes — CHANGES_REQUESTED** [review]
Could you please add `prefix` to the required constants @nopeless

**Comment by nopeless** [comment]
:barry: you can also suggest changes as well

**Comment by doublevcodes** [comment]
Is there a difference

**Comment by nopeless** [comment]
yes also i changed the thing now

**Review by doublevcodes — APPROVED** [review]
Ok, I'll merge now

**Pull request merged**
